# Generated by Django 4.1.3 on 2022-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_facebook',
            new_name='social_github',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_instagram',
            new_name='social_linkedin',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
