# Generated by Django 4.1.3 on 2022-12-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_social_facebook_profile_social_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_youtube',
        ),
    ]
